### ISSUE TITLE
StyleCI

### ISSUE THREAD

**Issue by GrahamCampbell** [phprest/phprest#13]
Are you having trouble configuring StyleCI? Is there anything I can help with?

**Comment by adammbalogh** [comment]
@GrahamCampbell I've just set an example config on StyleCI and it works great thanks!

**Comment by GrahamCampbell** [comment]
You do know the example config wasn;t actually intended to be used. It was just an example of what you can configure. It's actually totally broken.

**Comment by GrahamCampbell** [comment]
The "default" config would be:

``` yaml
preset: recommended

linting: true

finder:
  exclude:
    - storage
    - vendor
  name:
    - "*.php"
```

That's basically what get's used as a base, then everything else you configure get's applied on top.
